config/routes.rb
Rails.application.routes.draw do
  
  root 'main_controller#index'
  get  '/about',    to: 'static_pages#about'
  get  '/analyze',    to: 'analyzer#analyze'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sentiment_analysis.rb
class SentimentAnalysis
  
  attr_accessor :averageScore
  attr_accessor :averageSentiment
  attr_accessor :moodMap
  
end

app/models/tweet.rb
class Tweet
  
  attr_accessor :id
  attr_accessor :text
  attr_accessor :user
  attr_accessor :created_at  
  
end

app/models/twitter_user.rb
class TwitterUser

  attr_accessor :id  
  attr_accessor :name
  attr_accessor :screen_name
  attr_accessor :profile_image_url_https
  
end

app/controllers/analyzer_controller.rb
class AnalyzerController < ApplicationController
  
  def analyze
    @twitterUserName = params[:user]
    
    if @twitterUserName.blank?
      flash.now[:danger] = "The user name must no be empty"
    else
      begin 
        @twitterUser = findUserByName(@twitterUserName)
        @tweets = searchLast20UserRelatedTweets(@twitterUser)
        analyzeTweetsSentiment(@tweets)
      rescue Twitter::Error::NotFound
        flash.now[:danger] = "Sorry, this user was not found"
      rescue => e
        flash.now[:danger] = "Sorry, we had a problem retrieving this user tweets. Try again later, please."
        @apiError = true
        logger.error e.message
        e.backtrace.each { |line| logger.error line }
      end
    end
  end
  
  private
  
  def findUserByName(twitterUserName)
    return TwitterService.new.findUserByName(@twitterUserName)
  end
  
  def searchLast20UserRelatedTweets(twitterUser)
    return TwitterService.new.searchRecentUserRelatedTweets(twitterUser).take(20)
  end
  
  def analyzeTweetsSentiment (tweets)
    if tweets.nil? == false
      sentimentAnalysis = SentimentAnalysisService.new.analyzeTweetsSentiment(tweets)    
      
      @moodMap = sentimentAnalysis.moodMap
      @averageScore = sentimentAnalysis.averageScore
      @averageSentiment = sentimentAnalysis.averageSentiment
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/main_controller_controller.rb
class MainControllerController < ApplicationController
  
  layout 'main'
  
  def index
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/helpers/analyzer_helper.rb
module AnalyzerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_controller_helper.rb
module MainControllerHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/analyzer/analyze.html.erb
<% provide(:container_id, "analyze-container") %>

<% flash.each do |message_type, message| %>
  <div class="row flash-container">
    <div class="col-lg-12">
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    </div>
  </div> 
<% end %>

<% if @twitterUser.nil? == false && @apiError.blank? %>

  <div class="row">
    <div class="col-lg-6">
      <h1>
        <a class="twitter-user-heading" target="_blank" href="https://twitter.com/<%= @twitterUser.screen_name %>">
          <span class="author-avatar">
            <img class="image-avatar" src="<%= @twitterUser.profile_image_url_https %>">
          </span>
          <%= @twitterUser.screen_name %>
        </a>
      </h1>
    </div>
    
    <div class="col-lg-6" id="search-bar-analyse">
      <form action="/analyze">
        <div class="input-group">
          <input type="text" name="user" class="form-control" placeholder="Type the name of a twitter user here...">
          <span class="input-group-btn">
            <button class="btn btn-default" type="submit">Go!</button>
          </span>
        </div>
      </form>
    </div>
    
  </div>
  
  <%if @tweets.blank? == false %>
  
    <% tooltipScore = "A score greater than 0.1 represents a positive sentiment. Between -0.1 and 0.1, it is neutral. Less than -0.1 is negative." %>
    
    <div class="row" id="hype-meter" >
      <div class="col-lg-6">
        <strong>HypeMeter:</strong> <span class="<%= @averageSentiment %>-sentiment"><%= @averageSentiment %></span>
      </div>
    </div>
    
    <div class="row" id="hype-score" >
      <div class="col-lg-3">
        <div class="tooltipholder"><strong>Average Score:</strong> <span class="<%= @averageSentiment %>-sentiment"><%= @averageScore.round(2) %> </span> <span class="tooltiptext"><%= tooltipScore %></span></div>
      </div>
    </div>
    
    <div class="row headers">
      <div class="col-lg-6">
        Tweet
      </div>
      <div class="col-lg-3">
        <div class="tooltipholder">Score<span class="tooltiptext"><%= tooltipScore %></span></div>
      </div>
      <div class="col-lg-3">
        Sentiment
      </div>
    </div>
      
    <% @tweets.each do |tweet| %>
    <div class="row tweet-row">
      <div class="col-lg-6">
        
        <div class="tweet">
          
          <div>
            <a class="screen-name" target="_blank" href="https://twitter.com/<%= tweet.user.screen_name %>">
              <span class="author-avatar small-avatar">
                <img class="image-avatar" src="<%= tweet.user.profile_image_url_https %>">
              </span>
              <%= tweet.user.screen_name %>
            </a>
            
            <span class="tweet-time pull-right"><%= tweet.created_at.to_s.sub("\+0000", "") %></span>
          </div>
          
          <div>
            <a class="tweet-link" target="_blank" href="https://twitter.com/<%= tweet.user.screen_name.downcase %>/status/<%= tweet.id %>"><%= tweet.text %></a>
          </div>
          
        </div>
        
      </div>
      
      <div class="col-lg-3">
        <span class="<%= @moodMap[tweet.id][:sentiment] %>-score"> <%= @moodMap[tweet.id][:score].round(2) %> </span>
      </div>
      
      <div class="col-lg-3">
        <span class="<%= @moodMap[tweet.id][:sentiment] %>-sentiment"> <%= @moodMap[tweet.id][:sentiment] %> </span>
      </div>
    </div>
    <% end unless @tweets.blank?%>
  
  <% else %>
  
    <div class="row" id="no-tweets-warn">
      Sorry, this user has no recent related tweets in english. <a href="/analyze?user=madonna">Try a more popular one.</a>
    </div>
  
  <% end %>

<% else %>

  <div class="row">
    <div class="col-lg-6">
      <h2>Search:</h2>  
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6">
      <form action="/analyze">
        <div class="input-group">
          <input type="text" name="user" class="form-control" placeholder="Type the name of a twitter user here...">
          <span class="input-group-btn">
            <button class="btn btn-default" type="submit">Go!</button>
          </span>
        </div>
      </form>
    </div>
  </div>

<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <small>
      HypeScoop, the free sentiment analyzer.
    </small>
    <nav>
      <ul>
        <li><%= link_to "Home",    root_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_head.html.erb
<head>
  <title>HypeScoop</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all',
                                            'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
  <![endif]-->
</head>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "HypeScoop",  root_path , id: "logo", class: "navbar-brand" %>
    </div>
    
    <div id="navbar" class="navbar-collapse collapse">
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "About", about_path %></li>
        </ul>
      </nav>
    </div>
    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
  <body>
    <%= render 'layouts/header' %>
    
    <div class="container" id="<%= yield(:container_id) %>">
      <%= yield %>
    </div>
    
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
  <body>
    <%= render 'layouts/header' %>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/main_controller/index.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
    <h1>Welcome to HypeScoop</h1>
    <p>HypeScoop is a free tool that you can use to analyze the sentiment of the tweets related to any twitter user. <br> It can be a celebrity, a company, even yourself.</p>
    
    <div class="row">
      
      <div id="search-form-home" class="col-lg-6"> 
      
        <form action="/analyze">
          <div class="input-group">
            <input type="text" name="user" class="form-control" placeholder="Type the name of a twitter user here...">
            <span class="input-group-btn">
              <button class="btn btn-default" type="submit">Go!</button>
            </span>
          </div>
        </form>
      </div>
      
    </div>

  </div>
</div>


<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col-md-4">
      <h2>HypeMeter</h2>
      <p>Discover the HypeMeter and see whats is the overall sentiment about any user. Are people being neutral, positive or negative?</p>
      <p><a class="btn btn-default" href="/analyze?user=everlane" role="button">See an example &raquo;</a></p>
    </div>
    <div class="col-md-4">
      <h2>Free</h2>
      <p>HypeScoop is free. You will never pay anything to use it. Promise.</p>
      <p><a class="btn btn-default" href="/about" role="button">View details &raquo;</a></p>
   </div>
    <div class="col-md-4">
      <h2>Open Source</h2>
      <p>HypeScoop is open source. You can modify it, and do whatever you want.</p>
      <p><a class="btn btn-default" href="https://gitlab.com/vernisan/hype_scoop" role="button" target="_blank">View details &raquo;</a></p>
    </div>
  </div>

  <hr>

  <footer>
    <p>&copy; 2016 HypeScoop, Inc.</p>
  </footer>
</div>

app/views/static_pages/about.html.erb
<h1>About</h1>
<p>Some fancy about page</p>